const ROLE_NAMES = [
  'clinic_admin',
  'clinic_staff',
  'front_desk',
  'billing_staff',
];

const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_ASSIGN_CLINIC_ADMIN: 'users.assign.clinic_admin',
  USERS_ASSIGN_CLINIC_STAFF: 'users.assign.clinic_staff',
  USERS_ASSIGN_FRONT_DESK: 'users.assign.front_desk',
  USERS_ASSIGN_BILLING_STAFF: 'users.assign.billing_staff',
  PATIENTS_READ: 'patients.read',
  PATIENTS_CREATE: 'patients.create',
  PATIENTS_UPDATE: 'patients.update',
  RECORDS_READ: 'records.read',
  RECORDS_CREATE: 'records.create',
};

const ROLE_PERMISSIONS = {
  clinic_admin: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_ASSIGN_CLINIC_ADMIN,
    PERMISSIONS.USERS_ASSIGN_CLINIC_STAFF,
    PERMISSIONS.USERS_ASSIGN_FRONT_DESK,
    PERMISSIONS.USERS_ASSIGN_BILLING_STAFF,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.RECORDS_CREATE,
  ],
  clinic_staff: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.RECORDS_CREATE,
  ],
  front_desk: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_UPDATE,
  ],
  billing_staff: [
    PERMISSIONS.PATIENTS_READ,
  ],
};

const ASSIGN_PERMISSION_BY_ROLE = {
  clinic_admin: PERMISSIONS.USERS_ASSIGN_CLINIC_ADMIN,
  clinic_staff: PERMISSIONS.USERS_ASSIGN_CLINIC_STAFF,
  front_desk: PERMISSIONS.USERS_ASSIGN_FRONT_DESK,
  billing_staff: PERMISSIONS.USERS_ASSIGN_BILLING_STAFF,
};

module.exports = {
  ASSIGN_PERMISSION_BY_ROLE,
  PERMISSIONS,
  ROLE_NAMES,
  ROLE_PERMISSIONS,
};
