const EMPLOYMENT_STATUSES = ['active', 'inactive', 'pending'];
const EMPLOYMENT_TYPES = ['Full Time', 'Part Time', 'Contract'];
const LICENSE_STATUSES = ['active', 'inactive', 'pending_verification'];
const DAYS_OF_WEEK = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const PROVIDER_TYPES = [
  'Physician',
  'Nurse Practitioner',
  'Physician Assistant',
  'Therapist',
  'Registered Nurse',
  'Medical Assistant',
  'Lab Technician',
  'Front Desk',
  'Billing Staff',
  'Administrator',
  'Other',
];

const DEPARTMENTS = [
  'General Medicine',
  'Urgent Care',
  'Vaccination',
  'Lab Services',
  'Wound Care',
  'Chronic Care',
  'Front Office',
  'Billing',
  'Administration',
];

const PRIMARY_ROLES = [
  'Treating provider',
  'Supervising provider',
  'Procedure-only provider',
  'Lab-only staff',
  'Intake-only staff',
  'Administrative lead',
];

const POPULATION_FOCUSES = ['pediatrics', 'adults', 'geriatrics'];

const VISIT_TYPES = [
  'New patient visit',
  'Follow-up visit',
  'Same-day sick visit',
  'Preventive / wellness visit',
  'Chronic care follow-up',
  'Vaccination visit',
  'Lab review visit',
  'Procedure visit',
  'Telehealth visit',
];

const CLINICAL_CATEGORY_DEFINITIONS = [
  {
    name: 'Respiratory',
    description: 'Airways, breathing, lung, nose, throat, and sinus outpatient conditions.',
    details: [
      'Acute upper respiratory infection (URI)',
      'Common cold',
      'Influenza',
      'COVID-19',
      'Acute bronchitis',
      'Sinusitis',
      'Pharyngitis',
      'Strep throat',
      'Tonsillitis',
      'Allergic rhinitis',
      'Asthma follow-up',
      'Mild asthma exacerbation',
      'Cough, unspecified',
      'Shortness of breath, mild outpatient evaluation',
      'Viral syndrome',
    ],
  },
  {
    name: 'Musculoskeletal / Injury',
    description: 'Bones, joints, muscles, tendons, ligaments, and soft-tissue injuries.',
    details: [
      'Sprain',
      'Strain',
      'Fracture, suspected or confirmed',
      'Contusion',
      'Joint pain',
      'Back pain',
      'Neck pain',
      'Shoulder injury',
      'Knee injury',
      'Ankle injury',
      'Tendonitis',
      'Repetitive strain injury',
      'Muscle spasm',
      'Wrist pain',
      'Foot injury',
      'Minor fall injury',
    ],
  },
  {
    name: 'Infectious Diseases',
    description: 'General outpatient infection management across body systems.',
    details: [
      'Influenza',
      'COVID-19',
      'Strep throat',
      'Urinary tract infection',
      'Cellulitis',
      'Gastroenteritis',
      'Otitis media',
      'Conjunctivitis',
      'Skin abscess',
      'Viral syndrome',
      'Viral pharyngitis',
      'Bacterial pharyngitis',
      'Folliculitis',
      'Fungal skin infection',
      'Mild dehydration due to infection',
      'Parasitic suspicion, depending on clinic scope',
    ],
  },
  {
    name: 'Chronic Conditions',
    description: 'Ongoing disease management, repeat follow-up, and medication monitoring.',
    details: [
      'Diabetes',
      'Hypertension',
      'Hyperlipidemia',
      'Hypothyroidism',
      'Asthma, long-term management',
      'Chronic kidney disease, outpatient monitoring depending on clinic scope',
      'Obesity',
      'Prediabetes',
      'GERD, long-term management',
      'Chronic pain follow-up, depending on clinic scope',
    ],
  },
  {
    name: 'Preventive / Routine Care',
    description: 'Wellness, screening, follow-up, and preventive outpatient visits.',
    details: [
      'Annual physical exam',
      'Wellness visit',
      'Vaccination encounter',
      'Blood pressure screening',
      'Cholesterol screening',
      'Diabetes screening',
      'Routine follow-up with no acute complaint',
      'Preventive counseling visit',
      'School or work clearance exam',
      'Medication refill follow-up',
      'Smoking cessation counseling',
      'Weight management counseling',
    ],
  },
  {
    name: 'Gastrointestinal',
    description: 'Digestive complaints and common outpatient GI presentations.',
    details: [
      'Gastroenteritis',
      'Abdominal pain, unspecified',
      'Dyspepsia',
      'GERD',
      'Constipation',
      'Diarrhea',
      'Nausea/vomiting',
      'Viral gastroenteritis',
      'Food-related GI upset',
      'Gastritis',
      'Peptic ulcer disease suspicion',
      'H. pylori-related dyspepsia, depending on testing workflow',
      'IBS-type symptoms / functional GI complaint',
      'Hemorrhoid complaint, if clinic handles basic evaluation',
      'Dehydration, mild outpatient',
    ],
  },
  {
    name: 'Dermatology',
    description: 'Skin, rash, and minor outpatient dermatologic concerns.',
    details: [
      'Atopic dermatitis / eczema',
      'Contact dermatitis',
      'Rash, unspecified',
      'Urticaria / hives',
      'Acne',
      'Fungal skin infection',
      'Cellulitis',
      'Impetigo',
      'Folliculitis',
      'Furuncle / boil',
      'Abscess',
      'Psoriasis follow-up',
      'Insect bite reaction',
      'Seborrheic dermatitis',
      'Skin lesion requiring evaluation',
      'Warts',
      'Pityriasis rosea',
    ],
  },
  {
    name: 'Mental Health',
    description: 'Behavioral health screening, follow-up, basic management, or referral.',
    details: [
      'Anxiety',
      'Depression',
      'Adjustment disorder',
      'Insomnia',
      'Stress-related symptoms',
      'Panic symptoms',
      'Mood symptoms',
      'Behavioral health follow-up',
      'Medication follow-up for mental health, depending on clinic scope',
    ],
  },
  {
    name: 'Minor Procedures / Wound Care',
    description: 'Simple procedures, wound evaluation, and outpatient treatment tasks.',
    details: [
      'Laceration',
      'Abrasion',
      'Minor burn',
      'Wound check',
      'Dressing change',
      'Skin tear',
      'Puncture wound',
      'Bite wound evaluation',
      'Abscess',
      'Draining wound',
      'Superficial wound infection',
      'Post-procedure wound follow-up',
      'Embedded splinter / simple foreign body, depending on clinic scope',
    ],
  },
  {
    name: 'Lab-Driven Conditions',
    description: 'Cases where lab interpretation and follow-up are a major workflow driver.',
    details: [
      'Anemia',
      'Prediabetes',
      'Diabetes diagnosed by lab criteria',
      'Hyperlipidemia',
      'Electrolyte imbalance',
      'Thyroid disorder',
      'Abnormal liver function tests requiring follow-up',
      'Kidney function abnormality requiring outpatient follow-up',
      'Iron deficiency suspicion',
      'Abnormal CBC review',
      'Abnormal urinalysis review',
      'Infection confirmed or clarified by lab findings',
      'Medication monitoring abnormality',
    ],
  },
];

const SYSTEM_PERMISSIONS = [
  { code: 'employee.create', name: 'Create employees', description: 'Create employee records.', isCategoryScoped: false },
  { code: 'employee.edit', name: 'Edit employees', description: 'Edit employee records.', isCategoryScoped: false },
  { code: 'staff.supervise', name: 'Supervise staff', description: 'Supervise other patient-care staff and oversee delegated work.', isCategoryScoped: false },
  { code: 'patient.view', name: 'View patients', description: 'View patient records.', isCategoryScoped: true },
  { code: 'patient.assign', name: 'Assign patients', description: 'Assign patients to clinicians.', isCategoryScoped: true },
  { code: 'patient.discharge', name: 'Discharge patients', description: 'Discharge patients from care workflows.', isCategoryScoped: true },
  { code: 'handoff.receive', name: 'Receive handoff', description: 'Receive clinical handoffs between care-team queues.', isCategoryScoped: true },
  { code: 'chart.note.create', name: 'Create chart notes', description: 'Create chart notes.', isCategoryScoped: true },
  { code: 'chart.sign', name: 'Sign charts', description: 'Sign chart documentation.', isCategoryScoped: true },
  { code: 'vitals.record', name: 'Record vitals', description: 'Record vital signs and bedside observations.', isCategoryScoped: true },
  { code: 'careplan.update', name: 'Update care plan', description: 'Update treatment plans and follow-up instructions.', isCategoryScoped: true },
  { code: 'diagnosis.finalize', name: 'Finalize diagnoses', description: 'Finalize diagnosis outcomes for an encounter.', isCategoryScoped: true },
  { code: 'labs.order.create', name: 'Order labs', description: 'Create lab orders.', isCategoryScoped: true },
  { code: 'labs.results.review', name: 'Review lab results', description: 'Review lab results.', isCategoryScoped: true },
  { code: 'labs.results.approve', name: 'Approve lab results', description: 'Approve and finalize returned lab results.', isCategoryScoped: true },
  { code: 'billing.codes.view', name: 'View billing codes', description: 'View billing-code libraries.', isCategoryScoped: false },
  { code: 'billing.invoice.edit', name: 'Edit invoices', description: 'Edit billing invoices.', isCategoryScoped: false },
  { code: 'schedule.manage', name: 'Manage schedule', description: 'Manage schedules.', isCategoryScoped: false },
  { code: 'triage.update', name: 'Update triage', description: 'Update triage workflows.', isCategoryScoped: true },
  { code: 'vaccines.administer', name: 'Administer vaccines', description: 'Administer vaccine workflows.', isCategoryScoped: true },
  { code: 'woundcare.perform', name: 'Perform wound care', description: 'Perform wound-care treatment workflows.', isCategoryScoped: true },
  { code: 'orders.imaging.create', name: 'Create imaging order', description: 'Create imaging and diagnostic-study orders.', isCategoryScoped: true },
  { code: 'patient.checkin.manage', name: 'Manage patient check-in', description: 'Manage check-in workflows.', isCategoryScoped: false },
  { code: 'staff.queue.view', name: 'View staff queue', description: 'View staff queue workflows.', isCategoryScoped: false },
  { code: 'inventory.edit', name: 'Edit inventory', description: 'Edit inventory records.', isCategoryScoped: false },
  { code: 'prescription.create', name: 'Create prescriptions', description: 'Create prescriptions.', isCategoryScoped: true },
];

function buildWizardDefaults() {
  return {
    basicInfo: {
      accountRole: 'clinic_staff',
      email: '',
      firstName: '',
      lastName: '',
      password: '',
      phone: '',
    },
    clinicalCategories: {
      categories: ['Preventive / Routine Care'],
      detailsByCategory: {
        'Preventive / Routine Care': [
          'Annual physical exam',
          'Wellness visit',
          'Vaccination encounter',
          'Blood pressure screening',
          'Cholesterol screening',
          'Diabetes screening',
          'Routine follow-up with no acute complaint',
          'Preventive counseling visit',
          'School or work clearance exam',
          'Medication refill follow-up',
          'Smoking cessation counseling',
          'Weight management counseling',
        ],
      },
    },
    credentials: {
      boardCertification: '',
      deaNumber: '',
      degree: '',
      expirationDate: '',
      issuingState: '',
      licenseNumber: '',
      licenseStatus: 'active',
      licenseType: '',
      npiNumber: '',
      specialTraining: '',
      supportingDocuments: [],
      yearsOfExperience: '',
    },
    employmentProfile: {
      clinicLocationName: '',
      department: 'General Medicine',
      employmentType: 'Full Time',
      primaryRole: 'Treating provider',
      providerType: 'Physician',
      roleTitle: '',
      startDate: '',
      status: 'pending',
    },
    experience: {
      internalNotes: '',
      languagesSpoken: '',
      notes: '',
      populationFocus: ['adults'],
      previousSpecialties: '',
      yearsInPractice: '',
    },
    systemPermissions: [
      { code: 'patient.view', allowed: true },
      { code: 'chart.note.create', allowed: true },
    ],
    categoryPermissions: [],
    availability: {
      daysAvailable: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      endTime: '17:00',
      maxPatientsPerDay: '20',
      notes: '',
      startTime: '09:00',
      visitTypesAllowed: ['New patient visit', 'Follow-up visit'],
    },
  };
}

module.exports = {
  CLINICAL_CATEGORY_DEFINITIONS,
  DAYS_OF_WEEK,
  DEPARTMENTS,
  EMPLOYMENT_STATUSES,
  EMPLOYMENT_TYPES,
  LICENSE_STATUSES,
  POPULATION_FOCUSES,
  PRIMARY_ROLES,
  PROVIDER_TYPES,
  SYSTEM_PERMISSIONS,
  VISIT_TYPES,
  buildWizardDefaults,
};
