const EMPLOYMENT_STATUSES = ['active', 'inactive', 'pending'];
const EMPLOYMENT_TYPES = ['Full Time', 'Part Time', 'Contract', 'Per Diem'];
const LICENSE_STATUSES = ['active', 'inactive', 'pending_verification'];
const EMPLOYEE_TYPES = ['clinical', 'non_clinical'];
const DAYS_OF_WEEK = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const PROVIDER_TYPES = [
  'Physician',
  'Nurse Practitioner',
  'Physician Assistant',
  'Therapist',
  'Registered Nurse',
  'Medical Assistant',
  'Lab Technician',
  'Front Desk',
  'Billing Staff',
  'Administrator',
  'Other',
];

const DEPARTMENTS = [
  'General Medicine',
  'Urgent Care',
  'Vaccination',
  'Lab Services',
  'Wound Care',
  'Chronic Care',
  'Front Office',
  'Billing',
  'Administration',
  'Front Desk',
  'Scheduling',
  'Medical Records',
  'Human Resources',
  'Finance',
  'IT Support',
  'Maintenance',
  'Housekeeping',
  'Security',
  'Supply Chain',
  'Pharmacy Support',
  'Customer Service',
];

const PRIMARY_ROLES = [
  'Treating provider',
  'Supervising provider',
  'Procedure-only provider',
  'Lab-only staff',
  'Intake-only staff',
  'Administrative lead',
];

const POPULATION_FOCUSES = ['pediatrics', 'adults', 'geriatrics'];

const SHIFT_TYPES = ['Day', 'Evening', 'Night', 'Weekend', 'Rotating'];

const STAFF_ROLE_DEFINITIONS = [
  { department: 'Front Desk', name: 'Front Desk Coordinator' },
  { department: 'Front Desk', name: 'Receptionist' },
  { department: 'Front Desk', name: 'Patient Access Associate' },
  { department: 'Scheduling', name: 'Scheduler' },
  { department: 'Scheduling', name: 'Referral Scheduling Specialist' },
  { department: 'Scheduling', name: 'Template Coordinator' },
  { department: 'Billing', name: 'Billing Specialist' },
  { department: 'Billing', name: 'Revenue Cycle Associate' },
  { department: 'Billing', name: 'Payment Posting Clerk' },
  { department: 'Medical Records', name: 'Medical Records Specialist' },
  { department: 'Medical Records', name: 'Release Of Information Clerk' },
  { department: 'Medical Records', name: 'Document Control Coordinator' },
  { department: 'Human Resources', name: 'HR Coordinator' },
  { department: 'Human Resources', name: 'Recruiting Assistant' },
  { department: 'Human Resources', name: 'Workforce Operations Specialist' },
  { department: 'Finance', name: 'Finance Analyst' },
  { department: 'Finance', name: 'Payroll Coordinator' },
  { department: 'Finance', name: 'Accounts Specialist' },
  { department: 'IT Support', name: 'IT Support Technician' },
  { department: 'IT Support', name: 'Help Desk Specialist' },
  { department: 'IT Support', name: 'Systems Support Analyst' },
  { department: 'Maintenance', name: 'Maintenance Technician' },
  { department: 'Maintenance', name: 'Facilities Coordinator' },
  { department: 'Maintenance', name: 'Work Order Dispatcher' },
  { department: 'Housekeeping', name: 'Environmental Services Associate' },
  { department: 'Housekeeping', name: 'Housekeeping Lead' },
  { department: 'Housekeeping', name: 'Sanitation Coordinator' },
  { department: 'Security', name: 'Security Officer' },
  { department: 'Security', name: 'Security Dispatcher' },
  { department: 'Security', name: 'Access Control Specialist' },
  { department: 'Supply Chain', name: 'Supply Coordinator' },
  { department: 'Supply Chain', name: 'Inventory Associate' },
  { department: 'Supply Chain', name: 'Materials Management Clerk' },
  { department: 'Pharmacy Support', name: 'Pharmacy Support Clerk' },
  { department: 'Pharmacy Support', name: 'Medication Runner' },
  { department: 'Pharmacy Support', name: 'Inventory Support Technician' },
  { department: 'Customer Service', name: 'Customer Service Representative' },
  { department: 'Customer Service', name: 'Patient Relations Coordinator' },
  { department: 'Customer Service', name: 'Call Center Associate' },
  { department: 'Administration', name: 'Administrative Assistant' },
  { department: 'Administration', name: 'Office Secretary' },
  { department: 'Administration', name: 'Operations Coordinator' },
];

const OPERATIONAL_SERVICE_LINES = [
  'Reception',
  'Patient arrival',
  'Wayfinding',
  'Appointment scheduling',
  'Referral coordination',
  'Reminder calls',
  'Claims review',
  'Payment intake',
  'Billing follow-up',
  'Records requests',
  'Chart indexing',
  'Document scanning',
  'Onboarding',
  'Employee records',
  'Staffing support',
  'Payroll support',
  'Expense review',
  'Financial reporting',
  'Help desk',
  'Device setup',
  'System troubleshooting',
  'Repairs',
  'Facility rounds',
  'Equipment requests',
  'Cleaning coverage',
  'Room turnover',
  'Sanitation checks',
  'Access control',
  'Incident response',
  'Visitor safety',
  'Stock replenishment',
  'Receiving',
  'Inventory counts',
  'Medication routing',
  'Refill follow-up',
  'Pharmacy stock support',
  'Call handling',
  'Escalations',
  'Service recovery',
  'Executive support',
  'Office coordination',
  'Internal reporting',
];

const OPERATIONAL_SYSTEMS = [
  'Phone Console',
  'Patient Messaging',
  'Scheduling Board',
  'Billing Work Queue',
  'Records Request Queue',
  'Document Scanner',
  'HRIS',
  'Payroll Dashboard',
  'Help Desk Portal',
  'Asset Tracker',
  'Security Desk',
  'Facilities Work Order Board',
  'Inventory Dashboard',
  'Visitor Management',
];

const COMMUNICATION_CHANNELS = [
  'Front desk phone',
  'Secure internal chat',
  'Email',
  'Ticket queue',
  'Radio',
  'Customer service line',
  'Visitor desk',
  'Shared operations inbox',
];

const VISIT_TYPES = [
  'New patient visit',
  'Follow-up visit',
  'Same-day sick visit',
  'Preventive / wellness visit',
  'Chronic care follow-up',
  'Vaccination visit',
  'Lab review visit',
  'Procedure visit',
  'Telehealth visit',
];

const CLINICAL_CATEGORY_DEFINITIONS = [
  {
    name: 'Respiratory',
    description: 'Airways, breathing, lung, nose, throat, and sinus outpatient conditions.',
    details: [
      'Acute upper respiratory infection (URI)',
      'Common cold',
      'Influenza',
      'COVID-19',
      'Acute bronchitis',
      'Sinusitis',
      'Pharyngitis',
      'Strep throat',
      'Tonsillitis',
      'Allergic rhinitis',
      'Asthma follow-up',
      'Mild asthma exacerbation',
      'Cough, unspecified',
      'Shortness of breath, mild outpatient evaluation',
      'Viral syndrome',
    ],
  },
  {
    name: 'Musculoskeletal / Injury',
    description: 'Bones, joints, muscles, tendons, ligaments, and soft-tissue injuries.',
    details: [
      'Sprain',
      'Strain',
      'Fracture, suspected or confirmed',
      'Contusion',
      'Joint pain',
      'Back pain',
      'Neck pain',
      'Shoulder injury',
      'Knee injury',
      'Ankle injury',
      'Tendonitis',
      'Repetitive strain injury',
      'Muscle spasm',
      'Wrist pain',
      'Foot injury',
      'Minor fall injury',
    ],
  },
  {
    name: 'Infectious Diseases',
    description: 'General outpatient infection management across body systems.',
    details: [
      'Influenza',
      'COVID-19',
      'Strep throat',
      'Urinary tract infection',
      'Cellulitis',
      'Gastroenteritis',
      'Otitis media',
      'Conjunctivitis',
      'Skin abscess',
      'Viral syndrome',
      'Viral pharyngitis',
      'Bacterial pharyngitis',
      'Folliculitis',
      'Fungal skin infection',
      'Mild dehydration due to infection',
      'Parasitic suspicion, depending on clinic scope',
    ],
  },
  {
    name: 'Chronic Conditions',
    description: 'Ongoing disease management, repeat follow-up, and medication monitoring.',
    details: [
      'Diabetes',
      'Hypertension',
      'Hyperlipidemia',
      'Hypothyroidism',
      'Asthma, long-term management',
      'Chronic kidney disease, outpatient monitoring depending on clinic scope',
      'Obesity',
      'Prediabetes',
      'GERD, long-term management',
      'Chronic pain follow-up, depending on clinic scope',
    ],
  },
  {
    name: 'Preventive / Routine Care',
    description: 'Wellness, screening, follow-up, and preventive outpatient visits.',
    details: [
      'Annual physical exam',
      'Wellness visit',
      'Vaccination encounter',
      'Blood pressure screening',
      'Cholesterol screening',
      'Diabetes screening',
      'Routine follow-up with no acute complaint',
      'Preventive counseling visit',
      'School or work clearance exam',
      'Medication refill follow-up',
      'Smoking cessation counseling',
      'Weight management counseling',
    ],
  },
  {
    name: 'Gastrointestinal',
    description: 'Digestive complaints and common outpatient GI presentations.',
    details: [
      'Gastroenteritis',
      'Abdominal pain, unspecified',
      'Dyspepsia',
      'GERD',
      'Constipation',
      'Diarrhea',
      'Nausea/vomiting',
      'Viral gastroenteritis',
      'Food-related GI upset',
      'Gastritis',
      'Peptic ulcer disease suspicion',
      'H. pylori-related dyspepsia, depending on testing workflow',
      'IBS-type symptoms / functional GI complaint',
      'Hemorrhoid complaint, if clinic handles basic evaluation',
      'Dehydration, mild outpatient',
    ],
  },
  {
    name: 'Dermatology',
    description: 'Skin, rash, and minor outpatient dermatologic concerns.',
    details: [
      'Atopic dermatitis / eczema',
      'Contact dermatitis',
      'Rash, unspecified',
      'Urticaria / hives',
      'Acne',
      'Fungal skin infection',
      'Cellulitis',
      'Impetigo',
      'Folliculitis',
      'Furuncle / boil',
      'Abscess',
      'Psoriasis follow-up',
      'Insect bite reaction',
      'Seborrheic dermatitis',
      'Skin lesion requiring evaluation',
      'Warts',
      'Pityriasis rosea',
    ],
  },
  {
    name: 'Mental Health',
    description: 'Behavioral health screening, follow-up, basic management, or referral.',
    details: [
      'Anxiety',
      'Depression',
      'Adjustment disorder',
      'Insomnia',
      'Stress-related symptoms',
      'Panic symptoms',
      'Mood symptoms',
      'Behavioral health follow-up',
      'Medication follow-up for mental health, depending on clinic scope',
    ],
  },
  {
    name: 'Minor Procedures / Wound Care',
    description: 'Simple procedures, wound evaluation, and outpatient treatment tasks.',
    details: [
      'Laceration',
      'Abrasion',
      'Minor burn',
      'Wound check',
      'Dressing change',
      'Skin tear',
      'Puncture wound',
      'Bite wound evaluation',
      'Abscess',
      'Draining wound',
      'Superficial wound infection',
      'Post-procedure wound follow-up',
      'Embedded splinter / simple foreign body, depending on clinic scope',
    ],
  },
  {
    name: 'Lab-Driven Conditions',
    description: 'Cases where lab interpretation and follow-up are a major workflow driver.',
    details: [
      'Anemia',
      'Prediabetes',
      'Diabetes diagnosed by lab criteria',
      'Hyperlipidemia',
      'Electrolyte imbalance',
      'Thyroid disorder',
      'Abnormal liver function tests requiring follow-up',
      'Kidney function abnormality requiring outpatient follow-up',
      'Iron deficiency suspicion',
      'Abnormal CBC review',
      'Abnormal urinalysis review',
      'Infection confirmed or clarified by lab findings',
      'Medication monitoring abnormality',
    ],
  },
];

const SYSTEM_PERMISSIONS = [
  { code: 'employee.create', name: 'Create employees', description: 'Create employee records.', isCategoryScoped: false },
  { code: 'employee.edit', name: 'Edit employees', description: 'Edit employee records.', isCategoryScoped: false },
  { code: 'staff.supervise', name: 'Supervise staff', description: 'Supervise other patient-care staff and oversee delegated work.', isCategoryScoped: false },
  { code: 'patient.view', name: 'View patients', description: 'View patient records.', isCategoryScoped: true },
  { code: 'patient.assign', name: 'Assign patients', description: 'Assign patients to clinicians.', isCategoryScoped: true },
  { code: 'patient.discharge', name: 'Discharge patients', description: 'Discharge patients from care workflows.', isCategoryScoped: true },
  { code: 'handoff.receive', name: 'Receive handoff', description: 'Receive clinical handoffs between care-team queues.', isCategoryScoped: true },
  { code: 'chart.note.create', name: 'Create chart notes', description: 'Create chart notes.', isCategoryScoped: true },
  { code: 'chart.sign', name: 'Sign charts', description: 'Sign chart documentation.', isCategoryScoped: true },
  { code: 'vitals.record', name: 'Record vitals', description: 'Record vital signs and bedside observations.', isCategoryScoped: true },
  { code: 'careplan.update', name: 'Update care plan', description: 'Update treatment plans and follow-up instructions.', isCategoryScoped: true },
  { code: 'diagnosis.finalize', name: 'Finalize diagnoses', description: 'Finalize diagnosis outcomes for an encounter.', isCategoryScoped: true },
  { code: 'labs.order.create', name: 'Order labs', description: 'Create lab orders.', isCategoryScoped: true },
  { code: 'labs.results.review', name: 'Review lab results', description: 'Review lab results.', isCategoryScoped: true },
  { code: 'labs.results.approve', name: 'Approve lab results', description: 'Approve and finalize returned lab results.', isCategoryScoped: true },
  { code: 'billing.codes.view', name: 'View billing codes', description: 'View billing-code libraries.', isCategoryScoped: false },
  { code: 'billing.invoice.edit', name: 'Edit invoices', description: 'Edit billing invoices.', isCategoryScoped: false },
  { code: 'schedule.manage', name: 'Manage schedule', description: 'Manage schedules.', isCategoryScoped: false },
  { code: 'triage.update', name: 'Update triage', description: 'Update triage workflows.', isCategoryScoped: true },
  { code: 'vaccines.administer', name: 'Administer vaccines', description: 'Administer vaccine workflows.', isCategoryScoped: true },
  { code: 'woundcare.perform', name: 'Perform wound care', description: 'Perform wound-care treatment workflows.', isCategoryScoped: true },
  { code: 'orders.imaging.create', name: 'Create imaging order', description: 'Create imaging and diagnostic-study orders.', isCategoryScoped: true },
  { code: 'patient.checkin.manage', name: 'Manage patient check-in', description: 'Manage check-in workflows.', isCategoryScoped: false },
  { code: 'staff.queue.view', name: 'View staff queue', description: 'View staff queue workflows.', isCategoryScoped: false },
  { code: 'reception.desk.manage', name: 'Manage reception desk', description: 'Manage reception desk operations and front-desk coverage.', isCategoryScoped: false },
  { code: 'visitors.checkin.manage', name: 'Manage visitor check-in', description: 'Manage visitor check-in and access checkpoints.', isCategoryScoped: false },
  { code: 'customer.service.cases.manage', name: 'Manage service cases', description: 'Manage customer service requests and escalations.', isCategoryScoped: false },
  { code: 'medical.records.view', name: 'View medical records queue', description: 'View records-release and document-control workflows.', isCategoryScoped: false },
  { code: 'medical.records.edit', name: 'Update records workflow', description: 'Update records-release and document-processing workflows.', isCategoryScoped: false },
  { code: 'documents.scan.upload', name: 'Scan and upload documents', description: 'Scan and upload operational documents.', isCategoryScoped: false },
  { code: 'referrals.coordinate', name: 'Coordinate referrals', description: 'Coordinate referral scheduling and administrative follow-up.', isCategoryScoped: false },
  { code: 'finance.reports.view', name: 'View finance reports', description: 'View finance and reconciliation reports.', isCategoryScoped: false },
  { code: 'payroll.manage', name: 'Manage payroll support', description: 'Manage payroll support workflows and staffing pay inputs.', isCategoryScoped: false },
  { code: 'hr.employee.records.view', name: 'View employee records', description: 'View employee records and HR document workflows.', isCategoryScoped: false },
  { code: 'hr.employee.records.edit', name: 'Update employee records', description: 'Update employee records and onboarding workflows.', isCategoryScoped: false },
  { code: 'it.support.tickets.manage', name: 'Manage IT tickets', description: 'Manage IT support ticket workflows.', isCategoryScoped: false },
  { code: 'it.assets.manage', name: 'Manage IT assets', description: 'Manage devices, workstations, and technical asset tracking.', isCategoryScoped: false },
  { code: 'inventory.edit', name: 'Edit inventory', description: 'Edit inventory records.', isCategoryScoped: false },
  { code: 'supply.orders.manage', name: 'Manage supply orders', description: 'Manage supply ordering and receiving workflows.', isCategoryScoped: false },
  { code: 'facilities.workorders.manage', name: 'Manage facilities work orders', description: 'Manage maintenance and facilities work orders.', isCategoryScoped: false },
  { code: 'security.incident.manage', name: 'Manage security incidents', description: 'Manage security incidents and access event workflows.', isCategoryScoped: false },
  { code: 'housekeeping.assign', name: 'Assign housekeeping coverage', description: 'Assign housekeeping and sanitation coverage.', isCategoryScoped: false },
  { code: 'pharmacy.support.inventory', name: 'Support pharmacy inventory', description: 'Support pharmacy inventory and stock-routing workflows.', isCategoryScoped: false },
  { code: 'prescription.create', name: 'Create prescriptions', description: 'Create prescriptions.', isCategoryScoped: true },
];

function buildWizardDefaults() {
  return {
    basicInfo: {
      accountRole: 'clinic_staff',
      email: '',
      employeeType: 'clinical',
      firstName: '',
      lastName: '',
      password: '',
      phone: '',
    },
    clinicalCategories: {
      categories: ['Preventive / Routine Care'],
      detailsByCategory: {
        'Preventive / Routine Care': [
          'Annual physical exam',
          'Wellness visit',
          'Vaccination encounter',
          'Blood pressure screening',
          'Cholesterol screening',
          'Diabetes screening',
          'Routine follow-up with no acute complaint',
          'Preventive counseling visit',
          'School or work clearance exam',
          'Medication refill follow-up',
          'Smoking cessation counseling',
          'Weight management counseling',
        ],
      },
    },
    credentials: {
      boardCertification: '',
      deaNumber: '',
      degree: '',
      expirationDate: '',
      issuingState: '',
      licenseNumber: '',
      licenseStatus: 'active',
      licenseType: '',
      npiNumber: '',
      specialTraining: '',
      supportingDocuments: [],
      yearsOfExperience: '',
    },
    employmentProfile: {
      clinicLocationName: '',
      department: 'General Medicine',
      employmentType: 'Full Time',
      primaryRole: 'Treating provider',
      providerType: 'Physician',
      roleTitle: '',
      startDate: '',
      status: 'pending',
      staffRole: '',
    },
    experience: {
      internalNotes: '',
      languagesSpoken: '',
      notes: '',
      populationFocus: ['adults'],
      previousSpecialties: '',
      yearsInPractice: '',
    },
    systemPermissions: [
      { code: 'patient.view', allowed: true },
      { code: 'chart.note.create', allowed: true },
    ],
    categoryPermissions: [],
    availability: {
      daysAvailable: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      endTime: '17:00',
      maxPatientsPerDay: '20',
      notes: '',
      startTime: '09:00',
      visitTypesAllowed: ['New patient visit', 'Follow-up visit'],
    },
    operationalProfile: {
      communicationChannels: [],
      notes: '',
      serviceLines: [],
      shiftType: 'Day',
      systems: [],
      supervisor: '',
      workLocation: '',
    },
  };
}

module.exports = {
  CLINICAL_CATEGORY_DEFINITIONS,
  COMMUNICATION_CHANNELS,
  DAYS_OF_WEEK,
  DEPARTMENTS,
  EMPLOYEE_TYPES,
  EMPLOYMENT_STATUSES,
  EMPLOYMENT_TYPES,
  LICENSE_STATUSES,
  OPERATIONAL_SERVICE_LINES,
  OPERATIONAL_SYSTEMS,
  POPULATION_FOCUSES,
  PRIMARY_ROLES,
  PROVIDER_TYPES,
  SHIFT_TYPES,
  STAFF_ROLE_DEFINITIONS,
  SYSTEM_PERMISSIONS,
  VISIT_TYPES,
  buildWizardDefaults,
};
